import PDFDocument from 'pdfkit';

type PdfLine = {
  supplier?: string;
  type?: string;
  currency?: string;
  totalBets?: number;
  totalWins?: number;
  profit?: number;
  rate?: number;
  ggr?: number;
};

type PdfUnmatched = {
  gameUid?: string;
  reason?: string;
  currency?: string;
  totalBets?: number;
  totalWins?: number;
};

export type SettlementPdfSource = {
  prefix: string;
  month: string;
  name?: string;
  email?: string;
  billingRegion?: string;
  previousBalance?: number;
  totalGgr?: number;
  deducted?: number;
  newBalance?: number;
  lines?: PdfLine[];
  unmatched?: PdfUnmatched[];
  settledAt?: Date | string;
};

function money(value: number | undefined): string {
  return Number(value ?? 0).toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 4,
  });
}

export function buildSettlementPdf(settlement: SettlementPdfSource): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(18).text('Monthly GGR settlement');
    doc.moveDown(0.4);
    doc.fontSize(10).fillColor('#444444');
    doc.text(`User: ${settlement.name || '—'} (${settlement.prefix})`);
    doc.text(`Email: ${settlement.email || '—'}`);
    doc.text(`Month: ${settlement.month}`);
    doc.text(`Region: ${(settlement.billingRegion || '').toUpperCase() || '—'}`);
    if (settlement.settledAt) {
      doc.text(`Settled: ${new Date(settlement.settledAt).toISOString()}`);
    }

    doc.moveDown();
    doc.fillColor('#111111').fontSize(12).text('Prepaid summary');
    doc.fontSize(10).fillColor('#444444');
    doc.text(`Balance before: ${money(settlement.previousBalance)}`);
    doc.text(`GGR calculated: ${money(settlement.totalGgr)}`);
    doc.text(`Deducted: ${money(settlement.deducted)}`);
    doc.text(`Balance after: ${money(settlement.newBalance)}`);

    doc.moveDown();
    doc.fillColor('#111111').fontSize(12).text('Provider lines');
    doc.moveDown(0.3);
    doc.fontSize(8).fillColor('#444444');

    const lines = settlement.lines ?? [];
    if (lines.length === 0) {
      doc.text('No matched provider activity.');
    } else {
      const header = 'Supplier / type                  CCY     Bets        Wins      Profit   Rate      GGR';
      doc.font('Courier').text(header);
      doc.moveDown(0.2);
      for (const line of lines) {
        const label = `${line.supplier || ''} ${line.type || ''}`.trim().slice(0, 32).padEnd(32);
        const row = [
          label,
          String(line.currency || '').padEnd(6),
          money(line.totalBets).padStart(10),
          money(line.totalWins).padStart(10),
          money(line.profit).padStart(10),
          `${Number(line.rate ?? 0)}%`.padStart(7),
          money(line.ggr).padStart(10),
        ].join(' ');
        doc.text(row);
      }
      doc.font('Helvetica');
    }

    const unmatched = settlement.unmatched ?? [];
    if (unmatched.length > 0) {
      doc.moveDown();
      doc.font('Helvetica').fillColor('#111111').fontSize(12).text('Unmatched games (GGR 0)');
      doc.fontSize(8).fillColor('#444444');
      for (const row of unmatched) {
        doc.text(
          `${row.gameUid || '—'}  ${row.currency || ''}  bets ${money(row.totalBets)}  wins ${money(row.totalWins)}  ${row.reason || ''}`,
        );
      }
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#888888').text('Generated by ApiVexo monthly GGR settlement.');
    doc.end();
  });
}
